{Step} = zootorial

module.exports = new zootorial.Tutorial 
  id: 'galaxy_zoo_dashboard_tutorial'
  firstStep: 'map1'
  steps:
    welcome: new Step
      header: "Welcome"
      details: "Let's learn about the Galaxy Zoo Dashboard."
      nextButton: 'Start Tutorial'
      next: 'data1'
    data1: new Step
              header: 'Accessing Data'
              details: "The first step in tools is to load some data.<br><br>Start by clicking on the `Data' tab."
              attachment: 'center top a[data-drawer="data"] center 2.0'
              className: 'arrow-top'
              next: 'click li a[data-drawer="data"]': 'data2'
    data2: new Step
              header: 'Accessing Data'
              details: "You can either select data generated by Zooniverse users or data from the Sloan Digital Sky Survey.<br><br>For now, let’s select `Zooniverse'."
              attachment: 'left top a[data-tool="Zooniverse"] 0.0 3.0'
              className: 'arrow-top'
              next: 'click li a[data-tool="Zooniverse"]': 'data3'
    data3: new Step
              header: 'Accessing Data'
              details: "Now pick your data set. Try selecting `Recents'."
              attachment: 'center bottom a[data-target="recents"] center -2.0'
              className: 'arrow-bottom'
              next:
                  'click a[data-target="recents"]': 'data4'
                  'click a[data-target="favorites"]': 'data4'
    data4: new Step
              header: 'Accessing Data'
              details: "Click on `Import Data'"
              attachment: 'center top button.import center 2.0'
              className: 'arrow-top'
              next: 'click button.import': 'tools1'
    tools1: new Step
              header: 'Subject Viewer Tool'
              details: "Great - you've imported your data! Let’s look at what we have.<br><br>First, click the “Tools” tab, then select the `Subject Viewer'."
              attachment: 'left top a[data-drawer="tool"] 0.0 4.5'
              next: 'click a[data-tool="SubjectViewer"]': 'tools2'
    tools2: new Step
              header: 'Subject Viewer Tool'
              details: "We need to connect our Subject Viewer tool to the data. Click “Data source” and select “Zooniverse-1”."
              attachment: 'left center select.sources 1.2 0.0'
              className: 'arrow-left'
              next: 'change select.sources': 'tools3'
    tools3: new Step
              header: 'Subject Viewer Tool'
              details: "Click either `Previous' or `Next' to browse through objects in your dataset."
              attachment: 'left top button.previous center center'
              next: 'click button.next': 'map1',
                    'click button.previous': 'map1'
    map1: new Step
              header: 'Mapping Tool'
              details: "You can also view your objects on a map! Select the `Map' button in the `Tools' tab."
              attachment: 'center top a[data-drawer="data"] center 4.5'
              className: 'arrow-top'
              next: 'click a[data-tool="Mapper"]': 'map2'
    map2: new Step
              header: 'Mapping Tool'
              details: "Connect your data to the map by selecting “Zooniverse-1” again in the `Data Source' menu."
              attachment: 'left center select.sources 1.2 0.0'
              className: 'arrow-left'
              next: 'change select.sources': 'share1'
    map3: new Step
              header: 'Mapping Tool'
              details: "Zoom out to see all of your objects."
              attachment: 'left center setting.zoom 2.0 .5'
              className: 'arrow-left'
              next: 'change setting.zoom': 'map4'
    map4: new Step
              header: 'Mapping Tool'
              details: "You can change the wavelength of the background map here."
              attachment: 'left center a[data-drawer="data"] 2.0 .5'
              className: 'arrow-left'
              next: 'change setting.layer': 'share1'
    share1: new Step
              header: 'Sharing Data'
              details: "Want to share your map with someone? You can!<br><br>First, click on “Dashboards”."
              attachment: 'left center a[data-drawer="data"] 2.0 .5'
              className: 'arrow-left'
              next: 'click a[data-drawer="data"]': 'share2'
    share2: new Step
              header: 'Sharing Data'
              details: "Next, click on “Share”."
              attachment: 'left center a[data-drawer="data"] 2.0 .5'
              className: 'arrow-left'
              next: 'click a[data-drawer="data"]': 'share3'
    share3: new Step
              header: 'Sharing Data'
              details: "You can either cut and paste the url, or share it through Twitter or Facebook."
              attachment: 'left center a[data-drawer="data"] 2.0 .5'
              className: 'arrow-left'
              next: 'click a[data-drawer="data"]': 'finish'
    finish: new Step
              header: 'Finished!'
              details: "Congrats! You've examined your data, visualized it on a map, and learned how to share it.<br><br>Feel free to keep exploring and see everything else that Tools can do."
